apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dsm
resources:
  - frontend.yaml
images:
  - name: ghcr.io/jumarubea/dsm-web
    newTag: sha-59e7c851ae5b5dcbcee5894e6227d2e6ba087b0d
