apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dsm
resources:
  - frontend.yaml
images:
  - name: ghcr.io/jumarubea/dsm-web
    newTag: sha-a3bb79803f67aa5f2c054d8439301d49d399b277
